import type { Cud } from '../src/registry.js';

// Coverage generator configuration: which discovery documents produce
// generated tools, under which registry service name.

export interface GenApi {
  file: string;
  service: string;
}

// alertcenter (service-account-only auth) and drive v2 (superseded by v3)
// are deliberately not generated.
export const GEN_APIS: GenApi[] = [
  { file: 'admin.datatransfer_v1.json', service: 'admin' },
  { file: 'admin.directory_v1.json', service: 'admin' },
  { file: 'admin.reports_v1.json', service: 'admin' },
  { file: 'appsmarket.v2.json', service: 'appsmarket' },
  { file: 'calendar.v3.json', service: 'calendar' },
  { file: 'chat.v1.json', service: 'chat' },
  { file: 'classroom.v1.json', service: 'classroom' },
  { file: 'cloudidentity.v1.json', service: 'cloudidentity' },
  { file: 'cloudsearch.v1.json', service: 'cloudsearch' },
  { file: 'docs.v1.json', service: 'docs' },
  { file: 'drive.v3.json', service: 'drive' },
  { file: 'driveactivity.v2.json', service: 'driveactivity' },
  { file: 'drivelabels.v2.json', service: 'drivelabels' },
  { file: 'forms.v1.json', service: 'forms' },
  { file: 'gmail.v1.json', service: 'gmail' },
  { file: 'gmailpostmastertools.v1.json', service: 'postmaster' },
  { file: 'groupsmigration.v1.json', service: 'groupsmigration' },
  { file: 'groupssettings.v1.json', service: 'groupssettings' },
  { file: 'keep.v1.json', service: 'keep' },
  { file: 'licensing.v1.json', service: 'licensing' },
  { file: 'meet.v2.json', service: 'meet' },
  { file: 'people.v1.json', service: 'contacts' },
  { file: 'reseller.v1.json', service: 'reseller' },
  { file: 'script.v1.json', service: 'script' },
  { file: 'searchconsole.v1.json', service: 'searchconsole' },
  { file: 'sheets.v4.json', service: 'sheets' },
  { file: 'slides.v1.json', service: 'slides' },
  { file: 'tasks.v1.json', service: 'tasks' },
  { file: 'vault.v1.json', service: 'vault' },
  { file: 'workspaceevents.v1.json', service: 'workspaceevents' },
];

// Methods already implemented by curated tools — curated quality wins, the
// generator skips them. Sorted; keep it that way.
export const CURATED_METHOD_IDS: string[] = [
  'calendar.calendarList.list',
  'calendar.calendars.insert',
  'calendar.events.delete',
  'calendar.events.get',
  'calendar.events.insert',
  'calendar.events.instances',
  'calendar.events.list',
  'calendar.events.move',
  'calendar.events.patch',
  'calendar.events.quickAdd',
  'calendar.freebusy.query',
  'chat.spaces.get',
  'chat.spaces.list',
  'chat.spaces.messages.create',
  'chat.spaces.messages.list',
  'directory.groups.list',
  'directory.members.list',
  'directory.users.get',
  'directory.users.list',
  'directory.users.patch',
  'docs.documents.batchUpdate',
  'docs.documents.create',
  'docs.documents.get',
  'drive.about.get',
  'drive.accessproposals.list',
  'drive.accessproposals.resolve',
  'drive.comments.create',
  'drive.comments.delete',
  'drive.comments.get',
  'drive.comments.list',
  'drive.comments.update',
  'drive.drives.get',
  'drive.drives.list',
  'drive.files.copy',
  'drive.files.create',
  'drive.files.delete',
  'drive.files.emptyTrash',
  'drive.files.export',
  'drive.files.get',
  'drive.files.list',
  'drive.files.update',
  'drive.permissions.create',
  'drive.permissions.delete',
  'drive.permissions.list',
  'drive.permissions.update',
  'drive.replies.create',
  'drive.replies.delete',
  'drive.replies.list',
  'drive.replies.update',
  'drive.revisions.delete',
  'drive.revisions.list',
  'drive.revisions.update',
  'forms.forms.batchUpdate',
  'forms.forms.create',
  'forms.forms.get',
  'forms.forms.responses.get',
  'forms.forms.responses.list',
  'forms.forms.setPublishSettings',
  'forms.forms.watches.list',
  'gmail.users.drafts.create',
  'gmail.users.drafts.get',
  'gmail.users.drafts.list',
  'gmail.users.drafts.send',
  'gmail.users.getProfile',
  'gmail.users.history.list',
  'gmail.users.labels.create',
  'gmail.users.labels.delete',
  'gmail.users.labels.list',
  'gmail.users.messages.attachments.get',
  'gmail.users.messages.batchDelete',
  'gmail.users.messages.batchModify',
  'gmail.users.messages.delete',
  'gmail.users.messages.get',
  'gmail.users.messages.list',
  'gmail.users.messages.modify',
  'gmail.users.messages.send',
  'gmail.users.messages.trash',
  'gmail.users.settings.getVacation',
  'gmail.users.settings.updateVacation',
  'gmail.users.threads.get',
  'meet.conferenceRecords.get',
  'meet.conferenceRecords.list',
  'meet.conferenceRecords.recordings.list',
  'meet.conferenceRecords.transcripts.entries.list',
  'meet.conferenceRecords.transcripts.list',
  'people.contactGroups.create',
  'people.contactGroups.get',
  'people.contactGroups.list',
  'people.people.connections.list',
  'people.people.createContact',
  'people.people.deleteContact',
  'people.people.get',
  'people.people.getBatchGet',
  'people.people.searchContacts',
  'people.people.updateContact',
  'reports.activities.list',
  'searchconsole.urlInspection.index.inspect',
  'sheets.spreadsheets.batchUpdate',
  'sheets.spreadsheets.create',
  'sheets.spreadsheets.get',
  'sheets.spreadsheets.values.append',
  'sheets.spreadsheets.values.batchClear',
  'sheets.spreadsheets.values.batchGet',
  'sheets.spreadsheets.values.batchUpdate',
  'sheets.spreadsheets.values.clear',
  'sheets.spreadsheets.values.get',
  'sheets.spreadsheets.values.update',
  'slides.presentations.batchUpdate',
  'slides.presentations.create',
  'slides.presentations.get',
  'slides.presentations.pages.get',
  'slides.presentations.pages.getThumbnail',
  'tasks.tasklists.delete',
  'tasks.tasklists.get',
  'tasks.tasklists.insert',
  'tasks.tasklists.list',
  'tasks.tasklists.patch',
  'tasks.tasks.clear',
  'tasks.tasks.delete',
  'tasks.tasks.get',
  'tasks.tasks.insert',
  'tasks.tasks.list',
  'tasks.tasks.move',
  'tasks.tasks.patch',
  'webmasters.searchanalytics.query',
  'webmasters.sitemaps.delete',
  'webmasters.sitemaps.get',
  'webmasters.sitemaps.list',
  'webmasters.sitemaps.submit',
  'webmasters.sites.add',
  'webmasters.sites.delete',
  'webmasters.sites.get',
  'webmasters.sites.list',
];

// Corrections where HTTP-verb inference misreads a method's effect.
export const CUD_OVERRIDES: Record<string, Cud> = {};

// Replacement tool names for methodIds whose derived name exceeds the 64-char
// MCP limit or collides with another generated name.
export const NAME_OVERRIDES: Record<string, string> = {};

// Better model-facing descriptions than the Discovery text.
export const DESCRIPTION_OVERRIDES: Record<string, string> = {};
